import { StatusBar } from './../status-bar';
import { UserControlBase } from './../base/user-control-base';
import { Viewport } from '../../service/browser/viewport';
export declare class Blade extends UserControlBase {
    private browserService;
    viewport: Viewport;
    private _bladeId;
    bladeId: string;
    /** HACK:2016-11-06/hp: [angular-portal-blade] needs [this] as the controller.
    We don't know how to provide [this] to the directive.
    So we came up with this [vm] property.*/
    vm: any;
    statusBar: StatusBar;
    visibility: string;
    private watcherTitle;
    bladeContentHeight: number;
    bladeContentHeightInner: number;
    title: string;
    subTitle: string;
    width: string;
    widthStackLayout: {
        'width': string;
    };
    height: string;
    isInnerHtml: boolean;
    formblade: any;
    private _path;
    path: string;
    isCommandBrowse: boolean;
    commandBrowse: () => void;
    commandBrowseText: string;
    isCommandCancel: boolean;
    commandCancel: () => void;
    commandCancelText: string;
    isCommandCopy: boolean;
    isCommandCopyEnabled: boolean;
    commandCopy: () => void;
    commandCopyText: string;
    isCommandDelete: boolean;
    isCommandDeleteEnabled: boolean;
    commandDelete: () => void;
    commandDeleteText: string;
    isCommandDocument: boolean;
    commandDocument: () => void;
    commandDocumentText: string;
    isCommandDocument2: boolean;
    commandDocument2: () => void;
    commandDocument2Text: string;
    isCommandDocument3: boolean;
    commandDocument3: () => void;
    commandDocument3Text: string;
    isCommandDocument4: boolean;
    commandDocument4: () => void;
    commandDocument4Text: string;
    isCommandDocument5: boolean;
    commandDocument5: () => void;
    commandDocument5Text: string;
    isCommandNew: boolean;
    commandNew: () => void;
    commandNewText: string;
    isCommandOrder: boolean;
    commandOrder: () => void;
    commandOrderText: string;
    isCommandRestart: boolean;
    commandRestart: () => void;
    commandRestartText: string;
    isCommandSave: boolean;
    isCommandSaveEnabled: boolean;
    commandSave: () => void;
    commandSaveText: string;
    isCommandSearch: boolean;
    commandSearch: () => void;
    commandSearchText: string;
    isCommandStart: boolean;
    commandStart: () => void;
    commandStartText: string;
    isCommandStop: boolean;
    commandStop: () => void;
    commandStopText: string;
    isCommandSwap: boolean;
    commandSwap: () => void;
    commandSwapText: string;
    isCommandExcel: boolean;
    commandExcel: () => void;
    commandExcelText: string;
    constructor(path?: string, title?: string, subtitle?: string, width?: number);
    ngOnInit(): void;
    activate(): void;
    navigateTo(path: any): void;
    /** Must be overridden. */
    onNavigateTo(value: any): void;
    comparePaths(path1: string, path2: string): boolean;
    /** close blade. */
    close(): void;
    /** Override */
    onClose(): boolean;
    onCommandBrowse(): void;
    onCommandCancel(): void;
    onCommandCopy(): void;
    onCommandDelete(): void;
    onCommandDocument(): void;
    onCommandDocument2(): void;
    onCommandDocument3(): void;
    onCommandDocument4(): void;
    onCommandDocument5(): void;
    onCommandNew(): void;
    onCommandOrder(): void;
    onCommandRestart(): void;
    onCommandSave(): void;
    onCommandSearch(): void;
    onCommandStart(): void;
    onCommandStop(): void;
    onCommandSwap(): void;
    onCommandExcel(): void;
    private setBladeHeights;
}
