npm install --save @angular/common@2.4.5
npm install --save @angular/compiler@2.4.5
npm install --save @angular/compiler-cli@2.4.5
npm install --save @angular/core@2.4.5
npm install --save @angular/forms@2.4.5
npm install --save @angular/http@2.4.5
npm install --save @angular/platform-browser@2.4.5
npm install --save @angular/platform-browser-dynamic@2.4.5
npm install --save @angular/platform-server@2.4.5
npm install --save @angular/router@3.4.5
npm install --save @angular/upgrade@2.4.5
npm install --save systemjs@0.20.1
npm install --save-dev @types/node@7.0.4
npm install --save-dev tslint@4.4.1
npm install --save-dev @types/kendo-ui@2016.3.41
npm install --save-dev karma-webpack@2.0.2
npm install --save-dev gulp-uglify@2.0.1

npm install --save-dev @types/angular@1.6.2
npm install --save-dev jasmine@2.5.3
npm install --save-dev karma-webpack@2.0.1
npm install --save-dev typescript@2.1.5
